# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180206_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='log_file',
        ),
        migrations.AddField(
            model_name='log',
            name='conversation',
            field=models.TextField(blank=True, default='{ "conversation" : [] }', null=True),
        ),
    ]
