# Generated by Django 2.0.5 on 2018-05-29 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20180212_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateroom',
            name='users',
        ),
        migrations.AddField(
            model_name='room',
            name='has_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
